// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBitwardenClient creates a new instance of MockBitwardenClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBitwardenClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBitwardenClient {
	mock := &MockBitwardenClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBitwardenClient is an autogenerated mock type for the BitwardenClient type
type MockBitwardenClient struct {
	mock.Mock
}

type MockBitwardenClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBitwardenClient) EXPECT() *MockBitwardenClient_Expecter {
	return &MockBitwardenClient_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockBitwardenClient
func (_mock *MockBitwardenClient) Authenticate(ctx context.Context, accessToken string) error {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBitwardenClient_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockBitwardenClient_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockBitwardenClient_Expecter) Authenticate(ctx interface{}, accessToken interface{}) *MockBitwardenClient_Authenticate_Call {
	return &MockBitwardenClient_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, accessToken)}
}

func (_c *MockBitwardenClient_Authenticate_Call) Run(run func(ctx context.Context, accessToken string)) *MockBitwardenClient_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBitwardenClient_Authenticate_Call) Return(err error) *MockBitwardenClient_Authenticate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBitwardenClient_Authenticate_Call) RunAndReturn(run func(ctx context.Context, accessToken string) error) *MockBitwardenClient_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBitwardenClient
func (_mock *MockBitwardenClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBitwardenClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBitwardenClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBitwardenClient_Expecter) Close() *MockBitwardenClient_Close_Call {
	return &MockBitwardenClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBitwardenClient_Close_Call) Run(run func()) *MockBitwardenClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBitwardenClient_Close_Call) Return(err error) *MockBitwardenClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBitwardenClient_Close_Call) RunAndReturn(run func() error) *MockBitwardenClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockBitwardenClient
func (_mock *MockBitwardenClient) GetSecret(ctx context.Context, secretName string) (string, error) {
	ret := _mock.Called(ctx, secretName)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, secretName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, secretName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secretName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBitwardenClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockBitwardenClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretName string
func (_e *MockBitwardenClient_Expecter) GetSecret(ctx interface{}, secretName interface{}) *MockBitwardenClient_GetSecret_Call {
	return &MockBitwardenClient_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, secretName)}
}

func (_c *MockBitwardenClient_GetSecret_Call) Run(run func(ctx context.Context, secretName string)) *MockBitwardenClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBitwardenClient_GetSecret_Call) Return(s string, err error) *MockBitwardenClient_GetSecret_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBitwardenClient_GetSecret_Call) RunAndReturn(run func(ctx context.Context, secretName string) (string, error)) *MockBitwardenClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}
