// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretStore creates a new instance of MockSecretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretStore {
	mock := &MockSecretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretStore is an autogenerated mock type for the SecretStore type
type MockSecretStore struct {
	mock.Mock
}

type MockSecretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretStore) EXPECT() *MockSecretStore_Expecter {
	return &MockSecretStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSecretStore_Expecter) Delete(ctx interface{}, key interface{}) *MockSecretStore_Delete_Call {
	return &MockSecretStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockSecretStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockSecretStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretStore_Delete_Call) Return(err error) *MockSecretStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockSecretStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSecretStore_Expecter) Get(ctx interface{}, key interface{}) *MockSecretStore_Get_Call {
	return &MockSecretStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockSecretStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockSecretStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretStore_Get_Call) Return(s string, err error) *MockSecretStore_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecretStore_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockSecretStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSecretStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockSecretStore_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockSecretStore_Set_Call {
	return &MockSecretStore_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockSecretStore_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockSecretStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretStore_Set_Call) Return(err error) *MockSecretStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretStore_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockSecretStore_Set_Call {
	_c.Call.Return(run)
	return _c
}
