// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bdkmv/vanish/internal/sync"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncService creates a new instance of MockSyncService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncService {
	mock := &MockSyncService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncService is an autogenerated mock type for the SyncService type
type MockSyncService struct {
	mock.Mock
}

type MockSyncService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncService) EXPECT() *MockSyncService_Expecter {
	return &MockSyncService_Expecter{mock: &_m.Mock}
}

// Sync provides a mock function for the type MockSyncService
func (_mock *MockSyncService) Sync(ctx context.Context, job sync.SyncJob) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sync.SyncJob) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncService_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockSyncService_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - job sync.SyncJob
func (_e *MockSyncService_Expecter) Sync(ctx interface{}, job interface{}) *MockSyncService_Sync_Call {
	return &MockSyncService_Sync_Call{Call: _e.mock.On("Sync", ctx, job)}
}

func (_c *MockSyncService_Sync_Call) Run(run func(ctx context.Context, job sync.SyncJob)) *MockSyncService_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sync.SyncJob
		if args[1] != nil {
			arg1 = args[1].(sync.SyncJob)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncService_Sync_Call) Return(err error) *MockSyncService_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncService_Sync_Call) RunAndReturn(run func(ctx context.Context, job sync.SyncJob) error) *MockSyncService_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// SyncAll provides a mock function for the type MockSyncService
func (_mock *MockSyncService) SyncAll(ctx context.Context, jobs []sync.SyncJob) error {
	ret := _mock.Called(ctx, jobs)

	if len(ret) == 0 {
		panic("no return value specified for SyncAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []sync.SyncJob) error); ok {
		r0 = returnFunc(ctx, jobs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncService_SyncAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAll'
type MockSyncService_SyncAll_Call struct {
	*mock.Call
}

// SyncAll is a helper method to define mock.On call
//   - ctx context.Context
//   - jobs []sync.SyncJob
func (_e *MockSyncService_Expecter) SyncAll(ctx interface{}, jobs interface{}) *MockSyncService_SyncAll_Call {
	return &MockSyncService_SyncAll_Call{Call: _e.mock.On("SyncAll", ctx, jobs)}
}

func (_c *MockSyncService_SyncAll_Call) Run(run func(ctx context.Context, jobs []sync.SyncJob)) *MockSyncService_SyncAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []sync.SyncJob
		if args[1] != nil {
			arg1 = args[1].([]sync.SyncJob)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncService_SyncAll_Call) Return(err error) *MockSyncService_SyncAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncService_SyncAll_Call) RunAndReturn(run func(ctx context.Context, jobs []sync.SyncJob) error) *MockSyncService_SyncAll_Call {
	_c.Call.Return(run)
	return _c
}
