// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTailscaleProvider creates a new instance of MockTailscaleProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTailscaleProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTailscaleProvider {
	mock := &MockTailscaleProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTailscaleProvider is an autogenerated mock type for the TailscaleProvider type
type MockTailscaleProvider struct {
	mock.Mock
}

type MockTailscaleProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTailscaleProvider) EXPECT() *MockTailscaleProvider_Expecter {
	return &MockTailscaleProvider_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTailscaleProvider
func (_mock *MockTailscaleProvider) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTailscaleProvider_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTailscaleProvider_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTailscaleProvider_Expecter) Close() *MockTailscaleProvider_Close_Call {
	return &MockTailscaleProvider_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTailscaleProvider_Close_Call) Run(run func()) *MockTailscaleProvider_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTailscaleProvider_Close_Call) Return(err error) *MockTailscaleProvider_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTailscaleProvider_Close_Call) RunAndReturn(run func() error) *MockTailscaleProvider_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Dial provides a mock function for the type MockTailscaleProvider
func (_mock *MockTailscaleProvider) Dial(ctx context.Context, network string, address string) (net.Conn, error) {
	ret := _mock.Called(ctx, network, address)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (net.Conn, error)); ok {
		return returnFunc(ctx, network, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) net.Conn); ok {
		r0 = returnFunc(ctx, network, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, network, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTailscaleProvider_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type MockTailscaleProvider_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
func (_e *MockTailscaleProvider_Expecter) Dial(ctx interface{}, network interface{}, address interface{}) *MockTailscaleProvider_Dial_Call {
	return &MockTailscaleProvider_Dial_Call{Call: _e.mock.On("Dial", ctx, network, address)}
}

func (_c *MockTailscaleProvider_Dial_Call) Run(run func(ctx context.Context, network string, address string)) *MockTailscaleProvider_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTailscaleProvider_Dial_Call) Return(conn net.Conn, err error) *MockTailscaleProvider_Dial_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockTailscaleProvider_Dial_Call) RunAndReturn(run func(ctx context.Context, network string, address string) (net.Conn, error)) *MockTailscaleProvider_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// LocalAddr provides a mock function for the type MockTailscaleProvider
func (_mock *MockTailscaleProvider) LocalAddr() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalAddr")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTailscaleProvider_LocalAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalAddr'
type MockTailscaleProvider_LocalAddr_Call struct {
	*mock.Call
}

// LocalAddr is a helper method to define mock.On call
func (_e *MockTailscaleProvider_Expecter) LocalAddr() *MockTailscaleProvider_LocalAddr_Call {
	return &MockTailscaleProvider_LocalAddr_Call{Call: _e.mock.On("LocalAddr")}
}

func (_c *MockTailscaleProvider_LocalAddr_Call) Run(run func()) *MockTailscaleProvider_LocalAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTailscaleProvider_LocalAddr_Call) Return(s string, err error) *MockTailscaleProvider_LocalAddr_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTailscaleProvider_LocalAddr_Call) RunAndReturn(run func() (string, error)) *MockTailscaleProvider_LocalAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockTailscaleProvider
func (_mock *MockTailscaleProvider) Start(ctx context.Context, authKey string, hostname string) error {
	ret := _mock.Called(ctx, authKey, hostname)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, authKey, hostname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTailscaleProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTailscaleProvider_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - authKey string
//   - hostname string
func (_e *MockTailscaleProvider_Expecter) Start(ctx interface{}, authKey interface{}, hostname interface{}) *MockTailscaleProvider_Start_Call {
	return &MockTailscaleProvider_Start_Call{Call: _e.mock.On("Start", ctx, authKey, hostname)}
}

func (_c *MockTailscaleProvider_Start_Call) Run(run func(ctx context.Context, authKey string, hostname string)) *MockTailscaleProvider_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTailscaleProvider_Start_Call) Return(err error) *MockTailscaleProvider_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTailscaleProvider_Start_Call) RunAndReturn(run func(ctx context.Context, authKey string, hostname string) error) *MockTailscaleProvider_Start_Call {
	_c.Call.Return(run)
	return _c
}
